<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.ABI</code>
 */
class ABI extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version = 1;</code>
     */
    private $version = '';
    /**
     * Generated from protobuf field <code>string language = 2;</code>
     */
    private $language = '';
    /**
     * Generated from protobuf field <code>repeated .types.Function functions = 3;</code>
     */
    private $functions;
    /**
     * Generated from protobuf field <code>repeated .types.StateVar state_variables = 4;</code>
     */
    private $state_variables;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *     @type string $language
     *     @type \Types\PBFunction[]|\Google\Protobuf\Internal\RepeatedField $functions
     *     @type \Types\StateVar[]|\Google\Protobuf\Internal\RepeatedField $state_variables
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language = 2;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>string language = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .types.Function functions = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFunctions()
    {
        return $this->functions;
    }

    /**
     * Generated from protobuf field <code>repeated .types.Function functions = 3;</code>
     * @param \Types\PBFunction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFunctions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\PBFunction::class);
        $this->functions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .types.StateVar state_variables = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStateVariables()
    {
        return $this->state_variables;
    }

    /**
     * Generated from protobuf field <code>repeated .types.StateVar state_variables = 4;</code>
     * @param \Types\StateVar[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStateVariables($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\StateVar::class);
        $this->state_variables = $arr;

        return $this;
    }

}

