<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.AccountVoteInfo</code>
 */
class AccountVoteInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.Staking staking = 1;</code>
     */
    private $staking = null;
    /**
     * Generated from protobuf field <code>repeated .types.VoteInfo voting = 2;</code>
     */
    private $voting;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\Staking $staking
     *     @type \Types\VoteInfo[]|\Google\Protobuf\Internal\RepeatedField $voting
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.Staking staking = 1;</code>
     * @return \Types\Staking
     */
    public function getStaking()
    {
        return $this->staking;
    }

    /**
     * Generated from protobuf field <code>.types.Staking staking = 1;</code>
     * @param \Types\Staking $var
     * @return $this
     */
    public function setStaking($var)
    {
        GPBUtil::checkMessage($var, \Types\Staking::class);
        $this->staking = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .types.VoteInfo voting = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVoting()
    {
        return $this->voting;
    }

    /**
     * Generated from protobuf field <code>repeated .types.VoteInfo voting = 2;</code>
     * @param \Types\VoteInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVoting($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\VoteInfo::class);
        $this->voting = $arr;

        return $this;
    }

}

