<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.AccountAndRoot</code>
 */
class AccountAndRoot extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Account = 1;</code>
     */
    private $Account = '';
    /**
     * Generated from protobuf field <code>bytes Root = 2;</code>
     */
    private $Root = '';
    /**
     * Generated from protobuf field <code>bool Compressed = 3;</code>
     */
    private $Compressed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Account
     *     @type string $Root
     *     @type bool $Compressed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Account = 1;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->Account;
    }

    /**
     * Generated from protobuf field <code>bytes Account = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, False);
        $this->Account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Root = 2;</code>
     * @return string
     */
    public function getRoot()
    {
        return $this->Root;
    }

    /**
     * Generated from protobuf field <code>bytes Root = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRoot($var)
    {
        GPBUtil::checkString($var, False);
        $this->Root = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Compressed = 3;</code>
     * @return bool
     */
    public function getCompressed()
    {
        return $this->Compressed;
    }

    /**
     * Generated from protobuf field <code>bool Compressed = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setCompressed($var)
    {
        GPBUtil::checkBool($var);
        $this->Compressed = $var;

        return $this;
    }

}

