<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.AccountProof</code>
 */
class AccountProof extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.State state = 1;</code>
     */
    private $state = null;
    /**
     * Generated from protobuf field <code>bool inclusion = 2;</code>
     */
    private $inclusion = false;
    /**
     * Generated from protobuf field <code>bytes key = 3;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>bytes proofKey = 4;</code>
     */
    private $proofKey = '';
    /**
     * Generated from protobuf field <code>bytes proofVal = 5;</code>
     */
    private $proofVal = '';
    /**
     * Generated from protobuf field <code>bytes bitmap = 6;</code>
     */
    private $bitmap = '';
    /**
     * Generated from protobuf field <code>uint32 height = 7;</code>
     */
    private $height = 0;
    /**
     * Generated from protobuf field <code>repeated bytes auditPath = 8;</code>
     */
    private $auditPath;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\State $state
     *     @type bool $inclusion
     *     @type string $key
     *     @type string $proofKey
     *     @type string $proofVal
     *     @type string $bitmap
     *     @type int $height
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $auditPath
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.State state = 1;</code>
     * @return \Types\State
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.types.State state = 1;</code>
     * @param \Types\State $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkMessage($var, \Types\State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool inclusion = 2;</code>
     * @return bool
     */
    public function getInclusion()
    {
        return $this->inclusion;
    }

    /**
     * Generated from protobuf field <code>bool inclusion = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setInclusion($var)
    {
        GPBUtil::checkBool($var);
        $this->inclusion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes proofKey = 4;</code>
     * @return string
     */
    public function getProofKey()
    {
        return $this->proofKey;
    }

    /**
     * Generated from protobuf field <code>bytes proofKey = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProofKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->proofKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes proofVal = 5;</code>
     * @return string
     */
    public function getProofVal()
    {
        return $this->proofVal;
    }

    /**
     * Generated from protobuf field <code>bytes proofVal = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProofVal($var)
    {
        GPBUtil::checkString($var, False);
        $this->proofVal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bitmap = 6;</code>
     * @return string
     */
    public function getBitmap()
    {
        return $this->bitmap;
    }

    /**
     * Generated from protobuf field <code>bytes bitmap = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBitmap($var)
    {
        GPBUtil::checkString($var, False);
        $this->bitmap = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 height = 7;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>uint32 height = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkUint32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes auditPath = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAuditPath()
    {
        return $this->auditPath;
    }

    /**
     * Generated from protobuf field <code>repeated bytes auditPath = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAuditPath($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->auditPath = $arr;

        return $this;
    }

}

