<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.BlockBodyPaged</code>
 */
class BlockBodyPaged extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 total = 1;</code>
     */
    private $total = 0;
    /**
     * Generated from protobuf field <code>uint32 offset = 2;</code>
     */
    private $offset = 0;
    /**
     * Generated from protobuf field <code>uint32 size = 3;</code>
     */
    private $size = 0;
    /**
     * Generated from protobuf field <code>.types.BlockBody body = 4;</code>
     */
    private $body = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $total
     *     @type int $offset
     *     @type int $size
     *     @type \Types\BlockBody $body
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 total = 1;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>uint32 total = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 offset = 2;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>uint32 offset = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkUint32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 size = 3;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>uint32 size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.BlockBody body = 4;</code>
     * @return \Types\BlockBody
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>.types.BlockBody body = 4;</code>
     * @param \Types\BlockBody $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkMessage($var, \Types\BlockBody::class);
        $this->body = $var;

        return $this;
    }

}

