<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.Block</code>
 */
class Block extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     */
    private $hash = '';
    /**
     * Generated from protobuf field <code>.types.BlockHeader header = 2;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>.types.BlockBody body = 3;</code>
     */
    private $body = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hash
     *     @type \Types\BlockHeader $header
     *     @type \Types\BlockBody $body
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.BlockHeader header = 2;</code>
     * @return \Types\BlockHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.types.BlockHeader header = 2;</code>
     * @param \Types\BlockHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Types\BlockHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.BlockBody body = 3;</code>
     * @return \Types\BlockBody
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>.types.BlockBody body = 3;</code>
     * @param \Types\BlockBody $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkMessage($var, \Types\BlockBody::class);
        $this->body = $var;

        return $this;
    }

}

