<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * BlockchainStatus is current status of blockchain
 *
 * Generated from protobuf message <code>types.BlockchainStatus</code>
 */
class BlockchainStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes best_block_hash = 1;</code>
     */
    private $best_block_hash = '';
    /**
     * Generated from protobuf field <code>uint64 best_height = 2;</code>
     */
    private $best_height = 0;
    /**
     * Generated from protobuf field <code>string consensus_info = 3;</code>
     */
    private $consensus_info = '';
    /**
     * Generated from protobuf field <code>bytes best_chain_id_hash = 4;</code>
     */
    private $best_chain_id_hash = '';
    /**
     * Generated from protobuf field <code>.types.ChainInfo chain_info = 5;</code>
     */
    private $chain_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $best_block_hash
     *     @type int|string $best_height
     *     @type string $consensus_info
     *     @type string $best_chain_id_hash
     *     @type \Types\ChainInfo $chain_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes best_block_hash = 1;</code>
     * @return string
     */
    public function getBestBlockHash()
    {
        return $this->best_block_hash;
    }

    /**
     * Generated from protobuf field <code>bytes best_block_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBestBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->best_block_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 best_height = 2;</code>
     * @return int|string
     */
    public function getBestHeight()
    {
        return $this->best_height;
    }

    /**
     * Generated from protobuf field <code>uint64 best_height = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBestHeight($var)
    {
        GPBUtil::checkUint64($var);
        $this->best_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string consensus_info = 3;</code>
     * @return string
     */
    public function getConsensusInfo()
    {
        return $this->consensus_info;
    }

    /**
     * Generated from protobuf field <code>string consensus_info = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setConsensusInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->consensus_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes best_chain_id_hash = 4;</code>
     * @return string
     */
    public function getBestChainIdHash()
    {
        return $this->best_chain_id_hash;
    }

    /**
     * Generated from protobuf field <code>bytes best_chain_id_hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBestChainIdHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->best_chain_id_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.ChainInfo chain_info = 5;</code>
     * @return \Types\ChainInfo
     */
    public function getChainInfo()
    {
        return $this->chain_info;
    }

    /**
     * Generated from protobuf field <code>.types.ChainInfo chain_info = 5;</code>
     * @param \Types\ChainInfo $var
     * @return $this
     */
    public function setChainInfo($var)
    {
        GPBUtil::checkMessage($var, \Types\ChainInfo::class);
        $this->chain_info = $var;

        return $this;
    }

}

