<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.BlockBodyParams</code>
 */
class BlockBodyParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes hashornumber = 1;</code>
     */
    private $hashornumber = '';
    /**
     * Generated from protobuf field <code>.types.PageParams paging = 2;</code>
     */
    private $paging = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hashornumber
     *     @type \Types\PageParams $paging
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes hashornumber = 1;</code>
     * @return string
     */
    public function getHashornumber()
    {
        return $this->hashornumber;
    }

    /**
     * Generated from protobuf field <code>bytes hashornumber = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHashornumber($var)
    {
        GPBUtil::checkString($var, False);
        $this->hashornumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.PageParams paging = 2;</code>
     * @return \Types\PageParams
     */
    public function getPaging()
    {
        return $this->paging;
    }

    /**
     * Generated from protobuf field <code>.types.PageParams paging = 2;</code>
     * @param \Types\PageParams $var
     * @return $this
     */
    public function setPaging($var)
    {
        GPBUtil::checkMessage($var, \Types\PageParams::class);
        $this->paging = $var;

        return $this;
    }

}

