<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.BlockMetadata</code>
 */
class BlockMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     */
    private $hash = '';
    /**
     * Generated from protobuf field <code>.types.BlockHeader header = 2;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>int32 txcount = 3;</code>
     */
    private $txcount = 0;
    /**
     * blocksize in bytes
     *
     * Generated from protobuf field <code>int64 size = 4;</code>
     */
    private $size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hash
     *     @type \Types\BlockHeader $header
     *     @type int $txcount
     *     @type int|string $size
     *           blocksize in bytes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.BlockHeader header = 2;</code>
     * @return \Types\BlockHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.types.BlockHeader header = 2;</code>
     * @param \Types\BlockHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Types\BlockHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 txcount = 3;</code>
     * @return int
     */
    public function getTxcount()
    {
        return $this->txcount;
    }

    /**
     * Generated from protobuf field <code>int32 txcount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTxcount($var)
    {
        GPBUtil::checkInt32($var);
        $this->txcount = $var;

        return $this;
    }

    /**
     * blocksize in bytes
     *
     * Generated from protobuf field <code>int64 size = 4;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * blocksize in bytes
     *
     * Generated from protobuf field <code>int64 size = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;

        return $this;
    }

}

