<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ChainInfo returns chain configuration
 *
 * Generated from protobuf message <code>types.ChainInfo</code>
 */
class ChainInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.ChainId id = 1;</code>
     */
    private $id = null;
    /**
     * Generated from protobuf field <code>uint32 bpNumber = 2;</code>
     */
    private $bpNumber = 0;
    /**
     * Generated from protobuf field <code>uint64 maxblocksize = 3;</code>
     */
    private $maxblocksize = 0;
    /**
     * Generated from protobuf field <code>bytes maxtokens = 4;</code>
     */
    private $maxtokens = '';
    /**
     * Generated from protobuf field <code>bytes stakingminimum = 5;</code>
     */
    private $stakingminimum = '';
    /**
     * Generated from protobuf field <code>bytes totalstaking = 6;</code>
     */
    private $totalstaking = '';
    /**
     * Generated from protobuf field <code>bytes gasprice = 7;</code>
     */
    private $gasprice = '';
    /**
     * Generated from protobuf field <code>bytes nameprice = 8;</code>
     */
    private $nameprice = '';
    /**
     * Generated from protobuf field <code>bytes totalvotingpower = 9;</code>
     */
    private $totalvotingpower = '';
    /**
     * Generated from protobuf field <code>bytes votingreward = 10;</code>
     */
    private $votingreward = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\ChainId $id
     *     @type int $bpNumber
     *     @type int|string $maxblocksize
     *     @type string $maxtokens
     *     @type string $stakingminimum
     *     @type string $totalstaking
     *     @type string $gasprice
     *     @type string $nameprice
     *     @type string $totalvotingpower
     *     @type string $votingreward
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.ChainId id = 1;</code>
     * @return \Types\ChainId
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>.types.ChainId id = 1;</code>
     * @param \Types\ChainId $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \Types\ChainId::class);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 bpNumber = 2;</code>
     * @return int
     */
    public function getBpNumber()
    {
        return $this->bpNumber;
    }

    /**
     * Generated from protobuf field <code>uint32 bpNumber = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBpNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->bpNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 maxblocksize = 3;</code>
     * @return int|string
     */
    public function getMaxblocksize()
    {
        return $this->maxblocksize;
    }

    /**
     * Generated from protobuf field <code>uint64 maxblocksize = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxblocksize($var)
    {
        GPBUtil::checkUint64($var);
        $this->maxblocksize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes maxtokens = 4;</code>
     * @return string
     */
    public function getMaxtokens()
    {
        return $this->maxtokens;
    }

    /**
     * Generated from protobuf field <code>bytes maxtokens = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxtokens($var)
    {
        GPBUtil::checkString($var, False);
        $this->maxtokens = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes stakingminimum = 5;</code>
     * @return string
     */
    public function getStakingminimum()
    {
        return $this->stakingminimum;
    }

    /**
     * Generated from protobuf field <code>bytes stakingminimum = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStakingminimum($var)
    {
        GPBUtil::checkString($var, False);
        $this->stakingminimum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes totalstaking = 6;</code>
     * @return string
     */
    public function getTotalstaking()
    {
        return $this->totalstaking;
    }

    /**
     * Generated from protobuf field <code>bytes totalstaking = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalstaking($var)
    {
        GPBUtil::checkString($var, False);
        $this->totalstaking = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes gasprice = 7;</code>
     * @return string
     */
    public function getGasprice()
    {
        return $this->gasprice;
    }

    /**
     * Generated from protobuf field <code>bytes gasprice = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setGasprice($var)
    {
        GPBUtil::checkString($var, False);
        $this->gasprice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes nameprice = 8;</code>
     * @return string
     */
    public function getNameprice()
    {
        return $this->nameprice;
    }

    /**
     * Generated from protobuf field <code>bytes nameprice = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNameprice($var)
    {
        GPBUtil::checkString($var, False);
        $this->nameprice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes totalvotingpower = 9;</code>
     * @return string
     */
    public function getTotalvotingpower()
    {
        return $this->totalvotingpower;
    }

    /**
     * Generated from protobuf field <code>bytes totalvotingpower = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalvotingpower($var)
    {
        GPBUtil::checkString($var, False);
        $this->totalvotingpower = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes votingreward = 10;</code>
     * @return string
     */
    public function getVotingreward()
    {
        return $this->votingreward;
    }

    /**
     * Generated from protobuf field <code>bytes votingreward = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setVotingreward($var)
    {
        GPBUtil::checkString($var, False);
        $this->votingreward = $var;

        return $this;
    }

}

