<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ChainStats corresponds to a chain statistics report.
 *
 * Generated from protobuf message <code>types.ChainStats</code>
 */
class ChainStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string report = 1;</code>
     */
    private $report = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $report
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string report = 1;</code>
     * @return string
     */
    public function getReport()
    {
        return $this->report;
    }

    /**
     * Generated from protobuf field <code>string report = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReport($var)
    {
        GPBUtil::checkString($var, True);
        $this->report = $var;

        return $this;
    }

}

