<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     */
    private $contractAddress = '';
    /**
     * Generated from protobuf field <code>string eventName = 2;</code>
     */
    private $eventName = '';
    /**
     * Generated from protobuf field <code>string jsonArgs = 3;</code>
     */
    private $jsonArgs = '';
    /**
     * Generated from protobuf field <code>int32 eventIdx = 4;</code>
     */
    private $eventIdx = 0;
    /**
     * Generated from protobuf field <code>bytes txHash = 5;</code>
     */
    private $txHash = '';
    /**
     * Generated from protobuf field <code>bytes blockHash = 6;</code>
     */
    private $blockHash = '';
    /**
     * Generated from protobuf field <code>uint64 blockNo = 7;</code>
     */
    private $blockNo = 0;
    /**
     * Generated from protobuf field <code>int32 txIndex = 8;</code>
     */
    private $txIndex = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $contractAddress
     *     @type string $eventName
     *     @type string $jsonArgs
     *     @type int $eventIdx
     *     @type string $txHash
     *     @type string $blockHash
     *     @type int|string $blockNo
     *     @type int $txIndex
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     * @return string
     */
    public function getContractAddress()
    {
        return $this->contractAddress;
    }

    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContractAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->contractAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string eventName = 2;</code>
     * @return string
     */
    public function getEventName()
    {
        return $this->eventName;
    }

    /**
     * Generated from protobuf field <code>string eventName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEventName($var)
    {
        GPBUtil::checkString($var, True);
        $this->eventName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jsonArgs = 3;</code>
     * @return string
     */
    public function getJsonArgs()
    {
        return $this->jsonArgs;
    }

    /**
     * Generated from protobuf field <code>string jsonArgs = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setJsonArgs($var)
    {
        GPBUtil::checkString($var, True);
        $this->jsonArgs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 eventIdx = 4;</code>
     * @return int
     */
    public function getEventIdx()
    {
        return $this->eventIdx;
    }

    /**
     * Generated from protobuf field <code>int32 eventIdx = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEventIdx($var)
    {
        GPBUtil::checkInt32($var);
        $this->eventIdx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes txHash = 5;</code>
     * @return string
     */
    public function getTxHash()
    {
        return $this->txHash;
    }

    /**
     * Generated from protobuf field <code>bytes txHash = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTxHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->txHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes blockHash = 6;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->blockHash;
    }

    /**
     * Generated from protobuf field <code>bytes blockHash = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->blockHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 blockNo = 7;</code>
     * @return int|string
     */
    public function getBlockNo()
    {
        return $this->blockNo;
    }

    /**
     * Generated from protobuf field <code>uint64 blockNo = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlockNo($var)
    {
        GPBUtil::checkUint64($var);
        $this->blockNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 txIndex = 8;</code>
     * @return int
     */
    public function getTxIndex()
    {
        return $this->txIndex;
    }

    /**
     * Generated from protobuf field <code>int32 txIndex = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setTxIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->txIndex = $var;

        return $this;
    }

}

