<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.FilterInfo</code>
 */
class FilterInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     */
    private $contractAddress = '';
    /**
     * Generated from protobuf field <code>string eventName = 2;</code>
     */
    private $eventName = '';
    /**
     * Generated from protobuf field <code>uint64 blockfrom = 3;</code>
     */
    private $blockfrom = 0;
    /**
     * Generated from protobuf field <code>uint64 blockto = 4;</code>
     */
    private $blockto = 0;
    /**
     * Generated from protobuf field <code>bool desc = 5;</code>
     */
    private $desc = false;
    /**
     * Generated from protobuf field <code>bytes argFilter = 6;</code>
     */
    private $argFilter = '';
    /**
     * Generated from protobuf field <code>int32 recentBlockCnt = 7;</code>
     */
    private $recentBlockCnt = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $contractAddress
     *     @type string $eventName
     *     @type int|string $blockfrom
     *     @type int|string $blockto
     *     @type bool $desc
     *     @type string $argFilter
     *     @type int $recentBlockCnt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     * @return string
     */
    public function getContractAddress()
    {
        return $this->contractAddress;
    }

    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContractAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->contractAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string eventName = 2;</code>
     * @return string
     */
    public function getEventName()
    {
        return $this->eventName;
    }

    /**
     * Generated from protobuf field <code>string eventName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEventName($var)
    {
        GPBUtil::checkString($var, True);
        $this->eventName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 blockfrom = 3;</code>
     * @return int|string
     */
    public function getBlockfrom()
    {
        return $this->blockfrom;
    }

    /**
     * Generated from protobuf field <code>uint64 blockfrom = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlockfrom($var)
    {
        GPBUtil::checkUint64($var);
        $this->blockfrom = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 blockto = 4;</code>
     * @return int|string
     */
    public function getBlockto()
    {
        return $this->blockto;
    }

    /**
     * Generated from protobuf field <code>uint64 blockto = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlockto($var)
    {
        GPBUtil::checkUint64($var);
        $this->blockto = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool desc = 5;</code>
     * @return bool
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * Generated from protobuf field <code>bool desc = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkBool($var);
        $this->desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes argFilter = 6;</code>
     * @return string
     */
    public function getArgFilter()
    {
        return $this->argFilter;
    }

    /**
     * Generated from protobuf field <code>bytes argFilter = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setArgFilter($var)
    {
        GPBUtil::checkString($var, False);
        $this->argFilter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 recentBlockCnt = 7;</code>
     * @return int
     */
    public function getRecentBlockCnt()
    {
        return $this->recentBlockCnt;
    }

    /**
     * Generated from protobuf field <code>int32 recentBlockCnt = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setRecentBlockCnt($var)
    {
        GPBUtil::checkInt32($var);
        $this->recentBlockCnt = $var;

        return $this;
    }

}

