<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.ImportFormat</code>
 */
class ImportFormat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.SingleBytes wif = 1;</code>
     */
    private $wif = null;
    /**
     * Generated from protobuf field <code>string oldpass = 2;</code>
     */
    private $oldpass = '';
    /**
     * Generated from protobuf field <code>string newpass = 3;</code>
     */
    private $newpass = '';
    /**
     * Generated from protobuf field <code>.types.SingleBytes keystore = 4;</code>
     */
    private $keystore = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\SingleBytes $wif
     *     @type string $oldpass
     *     @type string $newpass
     *     @type \Types\SingleBytes $keystore
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.SingleBytes wif = 1;</code>
     * @return \Types\SingleBytes
     */
    public function getWif()
    {
        return $this->wif;
    }

    /**
     * Generated from protobuf field <code>.types.SingleBytes wif = 1;</code>
     * @param \Types\SingleBytes $var
     * @return $this
     */
    public function setWif($var)
    {
        GPBUtil::checkMessage($var, \Types\SingleBytes::class);
        $this->wif = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string oldpass = 2;</code>
     * @return string
     */
    public function getOldpass()
    {
        return $this->oldpass;
    }

    /**
     * Generated from protobuf field <code>string oldpass = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOldpass($var)
    {
        GPBUtil::checkString($var, True);
        $this->oldpass = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string newpass = 3;</code>
     * @return string
     */
    public function getNewpass()
    {
        return $this->newpass;
    }

    /**
     * Generated from protobuf field <code>string newpass = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNewpass($var)
    {
        GPBUtil::checkString($var, True);
        $this->newpass = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.SingleBytes keystore = 4;</code>
     * @return \Types\SingleBytes
     */
    public function getKeystore()
    {
        return $this->keystore;
    }

    /**
     * Generated from protobuf field <code>.types.SingleBytes keystore = 4;</code>
     * @param \Types\SingleBytes $var
     * @return $this
     */
    public function setKeystore($var)
    {
        GPBUtil::checkMessage($var, \Types\SingleBytes::class);
        $this->keystore = $var;

        return $this;
    }

}

