<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.NodeReq</code>
 */
class NodeReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes timeout = 1;</code>
     */
    private $timeout = '';
    /**
     * Generated from protobuf field <code>bytes component = 2;</code>
     */
    private $component = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $timeout
     *     @type string $component
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes timeout = 1;</code>
     * @return string
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>bytes timeout = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkString($var, False);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes component = 2;</code>
     * @return string
     */
    public function getComponent()
    {
        return $this->component;
    }

    /**
     * Generated from protobuf field <code>bytes component = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setComponent($var)
    {
        GPBUtil::checkString($var, False);
        $this->component = $var;

        return $this;
    }

}

