<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.Function</code>
 */
class PBFunction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>repeated .types.FnArgument arguments = 2;</code>
     */
    private $arguments;
    /**
     * Generated from protobuf field <code>bool payable = 3;</code>
     */
    private $payable = false;
    /**
     * Generated from protobuf field <code>bool view = 4;</code>
     */
    private $view = false;
    /**
     * Generated from protobuf field <code>bool fee_delegation = 5;</code>
     */
    private $fee_delegation = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Types\FnArgument[]|\Google\Protobuf\Internal\RepeatedField $arguments
     *     @type bool $payable
     *     @type bool $view
     *     @type bool $fee_delegation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .types.FnArgument arguments = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArguments()
    {
        return $this->arguments;
    }

    /**
     * Generated from protobuf field <code>repeated .types.FnArgument arguments = 2;</code>
     * @param \Types\FnArgument[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArguments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\FnArgument::class);
        $this->arguments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool payable = 3;</code>
     * @return bool
     */
    public function getPayable()
    {
        return $this->payable;
    }

    /**
     * Generated from protobuf field <code>bool payable = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setPayable($var)
    {
        GPBUtil::checkBool($var);
        $this->payable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool view = 4;</code>
     * @return bool
     */
    public function getView()
    {
        return $this->view;
    }

    /**
     * Generated from protobuf field <code>bool view = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setView($var)
    {
        GPBUtil::checkBool($var);
        $this->view = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool fee_delegation = 5;</code>
     * @return bool
     */
    public function getFeeDelegation()
    {
        return $this->fee_delegation;
    }

    /**
     * Generated from protobuf field <code>bool fee_delegation = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setFeeDelegation($var)
    {
        GPBUtil::checkBool($var);
        $this->fee_delegation = $var;

        return $this;
    }

}

