<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.PeersParams</code>
 */
class PeersParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool noHidden = 1;</code>
     */
    private $noHidden = false;
    /**
     * Generated from protobuf field <code>bool showSelf = 2;</code>
     */
    private $showSelf = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $noHidden
     *     @type bool $showSelf
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool noHidden = 1;</code>
     * @return bool
     */
    public function getNoHidden()
    {
        return $this->noHidden;
    }

    /**
     * Generated from protobuf field <code>bool noHidden = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoHidden($var)
    {
        GPBUtil::checkBool($var);
        $this->noHidden = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool showSelf = 2;</code>
     * @return bool
     */
    public function getShowSelf()
    {
        return $this->showSelf;
    }

    /**
     * Generated from protobuf field <code>bool showSelf = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setShowSelf($var)
    {
        GPBUtil::checkBool($var);
        $this->showSelf = $var;

        return $this;
    }

}

