<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.Personal</code>
 */
class Personal extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string passphrase = 1;</code>
     */
    private $passphrase = '';
    /**
     * Generated from protobuf field <code>.types.Account account = 2;</code>
     */
    private $account = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $passphrase
     *     @type \Types\Account $account
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string passphrase = 1;</code>
     * @return string
     */
    public function getPassphrase()
    {
        return $this->passphrase;
    }

    /**
     * Generated from protobuf field <code>string passphrase = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPassphrase($var)
    {
        GPBUtil::checkString($var, True);
        $this->passphrase = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.Account account = 2;</code>
     * @return \Types\Account
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>.types.Account account = 2;</code>
     * @param \Types\Account $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkMessage($var, \Types\Account::class);
        $this->account = $var;

        return $this;
    }

}

