<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.Query</code>
 */
class Query extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     */
    private $contractAddress = '';
    /**
     * Generated from protobuf field <code>bytes queryinfo = 2;</code>
     */
    private $queryinfo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $contractAddress
     *     @type string $queryinfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     * @return string
     */
    public function getContractAddress()
    {
        return $this->contractAddress;
    }

    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContractAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->contractAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes queryinfo = 2;</code>
     * @return string
     */
    public function getQueryinfo()
    {
        return $this->queryinfo;
    }

    /**
     * Generated from protobuf field <code>bytes queryinfo = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryinfo($var)
    {
        GPBUtil::checkString($var, False);
        $this->queryinfo = $var;

        return $this;
    }

}

