<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.Receipt</code>
 */
class Receipt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     */
    private $contractAddress = '';
    /**
     * Generated from protobuf field <code>string status = 2;</code>
     */
    private $status = '';
    /**
     * Generated from protobuf field <code>string ret = 3;</code>
     */
    private $ret = '';
    /**
     * Generated from protobuf field <code>bytes txHash = 4;</code>
     */
    private $txHash = '';
    /**
     * Generated from protobuf field <code>bytes feeUsed = 5;</code>
     */
    private $feeUsed = '';
    /**
     * Generated from protobuf field <code>bytes cumulativeFeeUsed = 6;</code>
     */
    private $cumulativeFeeUsed = '';
    /**
     * Generated from protobuf field <code>bytes bloom = 7;</code>
     */
    private $bloom = '';
    /**
     * Generated from protobuf field <code>repeated .types.Event events = 8;</code>
     */
    private $events;
    /**
     * Generated from protobuf field <code>uint64 blockNo = 9;</code>
     */
    private $blockNo = 0;
    /**
     * Generated from protobuf field <code>bytes blockHash = 10;</code>
     */
    private $blockHash = '';
    /**
     * Generated from protobuf field <code>int32 txIndex = 11;</code>
     */
    private $txIndex = 0;
    /**
     * Generated from protobuf field <code>bytes from = 12;</code>
     */
    private $from = '';
    /**
     * Generated from protobuf field <code>bytes to = 13;</code>
     */
    private $to = '';
    /**
     * Generated from protobuf field <code>bool feeDelegation = 14;</code>
     */
    private $feeDelegation = false;
    /**
     * Generated from protobuf field <code>uint64 gasUsed = 15;</code>
     */
    private $gasUsed = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $contractAddress
     *     @type string $status
     *     @type string $ret
     *     @type string $txHash
     *     @type string $feeUsed
     *     @type string $cumulativeFeeUsed
     *     @type string $bloom
     *     @type \Types\Event[]|\Google\Protobuf\Internal\RepeatedField $events
     *     @type int|string $blockNo
     *     @type string $blockHash
     *     @type int $txIndex
     *     @type string $from
     *     @type string $to
     *     @type bool $feeDelegation
     *     @type int|string $gasUsed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     * @return string
     */
    public function getContractAddress()
    {
        return $this->contractAddress;
    }

    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContractAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->contractAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ret = 3;</code>
     * @return string
     */
    public function getRet()
    {
        return $this->ret;
    }

    /**
     * Generated from protobuf field <code>string ret = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRet($var)
    {
        GPBUtil::checkString($var, True);
        $this->ret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes txHash = 4;</code>
     * @return string
     */
    public function getTxHash()
    {
        return $this->txHash;
    }

    /**
     * Generated from protobuf field <code>bytes txHash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTxHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->txHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes feeUsed = 5;</code>
     * @return string
     */
    public function getFeeUsed()
    {
        return $this->feeUsed;
    }

    /**
     * Generated from protobuf field <code>bytes feeUsed = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFeeUsed($var)
    {
        GPBUtil::checkString($var, False);
        $this->feeUsed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes cumulativeFeeUsed = 6;</code>
     * @return string
     */
    public function getCumulativeFeeUsed()
    {
        return $this->cumulativeFeeUsed;
    }

    /**
     * Generated from protobuf field <code>bytes cumulativeFeeUsed = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCumulativeFeeUsed($var)
    {
        GPBUtil::checkString($var, False);
        $this->cumulativeFeeUsed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bloom = 7;</code>
     * @return string
     */
    public function getBloom()
    {
        return $this->bloom;
    }

    /**
     * Generated from protobuf field <code>bytes bloom = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setBloom($var)
    {
        GPBUtil::checkString($var, False);
        $this->bloom = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .types.Event events = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .types.Event events = 8;</code>
     * @param \Types\Event[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\Event::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 blockNo = 9;</code>
     * @return int|string
     */
    public function getBlockNo()
    {
        return $this->blockNo;
    }

    /**
     * Generated from protobuf field <code>uint64 blockNo = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlockNo($var)
    {
        GPBUtil::checkUint64($var);
        $this->blockNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes blockHash = 10;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->blockHash;
    }

    /**
     * Generated from protobuf field <code>bytes blockHash = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->blockHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 txIndex = 11;</code>
     * @return int
     */
    public function getTxIndex()
    {
        return $this->txIndex;
    }

    /**
     * Generated from protobuf field <code>int32 txIndex = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setTxIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->txIndex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes from = 12;</code>
     * @return string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>bytes from = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkString($var, False);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes to = 13;</code>
     * @return string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>bytes to = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, False);
        $this->to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool feeDelegation = 14;</code>
     * @return bool
     */
    public function getFeeDelegation()
    {
        return $this->feeDelegation;
    }

    /**
     * Generated from protobuf field <code>bool feeDelegation = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setFeeDelegation($var)
    {
        GPBUtil::checkBool($var);
        $this->feeDelegation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 gasUsed = 15;</code>
     * @return int|string
     */
    public function getGasUsed()
    {
        return $this->gasUsed;
    }

    /**
     * Generated from protobuf field <code>uint64 gasUsed = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGasUsed($var)
    {
        GPBUtil::checkUint64($var);
        $this->gasUsed = $var;

        return $this;
    }

}

