<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.Staking</code>
 */
class Staking extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes amount = 1;</code>
     */
    private $amount = '';
    /**
     * Generated from protobuf field <code>uint64 when = 2;</code>
     */
    private $when = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $amount
     *     @type int|string $when
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes amount = 1;</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>bytes amount = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, False);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 when = 2;</code>
     * @return int|string
     */
    public function getWhen()
    {
        return $this->when;
    }

    /**
     * Generated from protobuf field <code>uint64 when = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWhen($var)
    {
        GPBUtil::checkUint64($var);
        $this->when = $var;

        return $this;
    }

}

