<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.State</code>
 */
class State extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 nonce = 1;</code>
     */
    private $nonce = 0;
    /**
     * Generated from protobuf field <code>bytes balance = 2;</code>
     */
    private $balance = '';
    /**
     * Generated from protobuf field <code>bytes codeHash = 3;</code>
     */
    private $codeHash = '';
    /**
     * Generated from protobuf field <code>bytes storageRoot = 4;</code>
     */
    private $storageRoot = '';
    /**
     * Generated from protobuf field <code>uint64 sqlRecoveryPoint = 5;</code>
     */
    private $sqlRecoveryPoint = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $nonce
     *     @type string $balance
     *     @type string $codeHash
     *     @type string $storageRoot
     *     @type int|string $sqlRecoveryPoint
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 nonce = 1;</code>
     * @return int|string
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * Generated from protobuf field <code>uint64 nonce = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkUint64($var);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes balance = 2;</code>
     * @return string
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Generated from protobuf field <code>bytes balance = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkString($var, False);
        $this->balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes codeHash = 3;</code>
     * @return string
     */
    public function getCodeHash()
    {
        return $this->codeHash;
    }

    /**
     * Generated from protobuf field <code>bytes codeHash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCodeHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->codeHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes storageRoot = 4;</code>
     * @return string
     */
    public function getStorageRoot()
    {
        return $this->storageRoot;
    }

    /**
     * Generated from protobuf field <code>bytes storageRoot = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStorageRoot($var)
    {
        GPBUtil::checkString($var, False);
        $this->storageRoot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 sqlRecoveryPoint = 5;</code>
     * @return int|string
     */
    public function getSqlRecoveryPoint()
    {
        return $this->sqlRecoveryPoint;
    }

    /**
     * Generated from protobuf field <code>uint64 sqlRecoveryPoint = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSqlRecoveryPoint($var)
    {
        GPBUtil::checkUint64($var);
        $this->sqlRecoveryPoint = $var;

        return $this;
    }

}

