<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.StateQuery</code>
 */
class StateQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     */
    private $contractAddress = '';
    /**
     * Generated from protobuf field <code>bytes root = 3;</code>
     */
    private $root = '';
    /**
     * Generated from protobuf field <code>bool compressed = 4;</code>
     */
    private $compressed = false;
    /**
     * Generated from protobuf field <code>repeated bytes storageKeys = 5;</code>
     */
    private $storageKeys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $contractAddress
     *     @type string $root
     *     @type bool $compressed
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $storageKeys
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     * @return string
     */
    public function getContractAddress()
    {
        return $this->contractAddress;
    }

    /**
     * Generated from protobuf field <code>bytes contractAddress = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContractAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->contractAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes root = 3;</code>
     * @return string
     */
    public function getRoot()
    {
        return $this->root;
    }

    /**
     * Generated from protobuf field <code>bytes root = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRoot($var)
    {
        GPBUtil::checkString($var, False);
        $this->root = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool compressed = 4;</code>
     * @return bool
     */
    public function getCompressed()
    {
        return $this->compressed;
    }

    /**
     * Generated from protobuf field <code>bool compressed = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setCompressed($var)
    {
        GPBUtil::checkBool($var);
        $this->compressed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes storageKeys = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStorageKeys()
    {
        return $this->storageKeys;
    }

    /**
     * Generated from protobuf field <code>repeated bytes storageKeys = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStorageKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->storageKeys = $arr;

        return $this;
    }

}

