<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.StateQueryProof</code>
 */
class StateQueryProof extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.AccountProof contractProof = 1;</code>
     */
    private $contractProof = null;
    /**
     * Generated from protobuf field <code>repeated .types.ContractVarProof varProofs = 2;</code>
     */
    private $varProofs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\AccountProof $contractProof
     *     @type \Types\ContractVarProof[]|\Google\Protobuf\Internal\RepeatedField $varProofs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.AccountProof contractProof = 1;</code>
     * @return \Types\AccountProof
     */
    public function getContractProof()
    {
        return $this->contractProof;
    }

    /**
     * Generated from protobuf field <code>.types.AccountProof contractProof = 1;</code>
     * @param \Types\AccountProof $var
     * @return $this
     */
    public function setContractProof($var)
    {
        GPBUtil::checkMessage($var, \Types\AccountProof::class);
        $this->contractProof = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .types.ContractVarProof varProofs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVarProofs()
    {
        return $this->varProofs;
    }

    /**
     * Generated from protobuf field <code>repeated .types.ContractVarProof varProofs = 2;</code>
     * @param \Types\ContractVarProof[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVarProofs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\ContractVarProof::class);
        $this->varProofs = $arr;

        return $this;
    }

}

