<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TxIdx specifies a transaction's block hash and index within the block body
 *
 * Generated from protobuf message <code>types.TxIdx</code>
 */
class TxIdx extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes blockHash = 1;</code>
     */
    private $blockHash = '';
    /**
     * Generated from protobuf field <code>int32 idx = 2;</code>
     */
    private $idx = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $blockHash
     *     @type int $idx
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes blockHash = 1;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->blockHash;
    }

    /**
     * Generated from protobuf field <code>bytes blockHash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->blockHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 idx = 2;</code>
     * @return int
     */
    public function getIdx()
    {
        return $this->idx;
    }

    /**
     * Generated from protobuf field <code>int32 idx = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIdx($var)
    {
        GPBUtil::checkInt32($var);
        $this->idx = $var;

        return $this;
    }

}

