<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.TxInBlock</code>
 */
class TxInBlock extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.TxIdx txIdx = 1;</code>
     */
    private $txIdx = null;
    /**
     * Generated from protobuf field <code>.types.Tx tx = 2;</code>
     */
    private $tx = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\TxIdx $txIdx
     *     @type \Types\Tx $tx
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.TxIdx txIdx = 1;</code>
     * @return \Types\TxIdx
     */
    public function getTxIdx()
    {
        return $this->txIdx;
    }

    /**
     * Generated from protobuf field <code>.types.TxIdx txIdx = 1;</code>
     * @param \Types\TxIdx $var
     * @return $this
     */
    public function setTxIdx($var)
    {
        GPBUtil::checkMessage($var, \Types\TxIdx::class);
        $this->txIdx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.Tx tx = 2;</code>
     * @return \Types\Tx
     */
    public function getTx()
    {
        return $this->tx;
    }

    /**
     * Generated from protobuf field <code>.types.Tx tx = 2;</code>
     * @param \Types\Tx $var
     * @return $this
     */
    public function setTx($var)
    {
        GPBUtil::checkMessage($var, \Types\Tx::class);
        $this->tx = $var;

        return $this;
    }

}

