<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>types.VerifyStatus</code>
 */
class VerifyStatus
{
    /**
     * Generated from protobuf enum <code>VERIFY_STATUS_OK = 0;</code>
     */
    const VERIFY_STATUS_OK = 0;
    /**
     * Generated from protobuf enum <code>VERIFY_STATUS_SIGN_NOT_MATCH = 1;</code>
     */
    const VERIFY_STATUS_SIGN_NOT_MATCH = 1;
    /**
     *TODO: not yet impl
     *
     * Generated from protobuf enum <code>VERIFY_STATUS_INVALID_HASH = 2;</code>
     */
    const VERIFY_STATUS_INVALID_HASH = 2;

    private static $valueToName = [
        self::VERIFY_STATUS_OK => 'VERIFY_STATUS_OK',
        self::VERIFY_STATUS_SIGN_NOT_MATCH => 'VERIFY_STATUS_SIGN_NOT_MATCH',
        self::VERIFY_STATUS_INVALID_HASH => 'VERIFY_STATUS_INVALID_HASH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

