<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.VerifyResult</code>
 */
class VerifyResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.Tx tx = 1;</code>
     */
    private $tx = null;
    /**
     * Generated from protobuf field <code>.types.VerifyStatus error = 2;</code>
     */
    private $error = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\Tx $tx
     *     @type int $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.Tx tx = 1;</code>
     * @return \Types\Tx
     */
    public function getTx()
    {
        return $this->tx;
    }

    /**
     * Generated from protobuf field <code>.types.Tx tx = 1;</code>
     * @param \Types\Tx $var
     * @return $this
     */
    public function setTx($var)
    {
        GPBUtil::checkMessage($var, \Types\Tx::class);
        $this->tx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.VerifyStatus error = 2;</code>
     * @return int
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>.types.VerifyStatus error = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkEnum($var, \Types\VerifyStatus::class);
        $this->error = $var;

        return $this;
    }

}

