<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.Vote</code>
 */
class Vote extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes candidate = 1;</code>
     */
    private $candidate = '';
    /**
     * Generated from protobuf field <code>bytes amount = 2;</code>
     */
    private $amount = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $candidate
     *     @type string $amount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes candidate = 1;</code>
     * @return string
     */
    public function getCandidate()
    {
        return $this->candidate;
    }

    /**
     * Generated from protobuf field <code>bytes candidate = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCandidate($var)
    {
        GPBUtil::checkString($var, False);
        $this->candidate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes amount = 2;</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>bytes amount = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, False);
        $this->amount = $var;

        return $this;
    }

}

