<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.VoteList</code>
 */
class VoteList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .types.Vote votes = 1;</code>
     */
    private $votes;
    /**
     * Generated from protobuf field <code>string id = 2;</code>
     */
    private $id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\Vote[]|\Google\Protobuf\Internal\RepeatedField $votes
     *     @type string $id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .types.Vote votes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * Generated from protobuf field <code>repeated .types.Vote votes = 1;</code>
     * @param \Types\Vote[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVotes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\Vote::class);
        $this->votes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

}

